// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnvhpsjrdsxdoyiityea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudmhwc2pyZHN4ZG95aWl0eWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjQ5ODYsImV4cCI6MjA3MjAwMDk4Nn0.oVIGJlSfZMKBiMy4gC9JQTX4TQvTw4DfSemElO9E_tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});